# Generated by Django 5.1.4 on 2024-12-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApi', '0002_alter_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
    ]
